export function buildProjectEnvTemplate(example: boolean): string {
  const kittyApiKeyLine = "KITTY_API_KEY=replace-with-your-key";

  return [
    "# Kitty CLI environment template",
    example
      ? "# Copy this file to .kitty/.env and fill real credentials."
      : "# This file stores local runtime credentials for the current project.",
    example
      ? "# .kitty/.env.example may be committed; never commit .kitty/.env."
      : "# Keep secrets in this file only; do not commit it.",
    "# Non-model runtime settings are listed first; provider and model settings are at the bottom.",
    "",
    "# Telegram private chat settings",
    "KITTY_TELEGRAM_TOKEN=replace-with-your-token",
    "KITTY_TELEGRAM_ALLOWED_USER_IDS=replace-with-your-telegram-user-id",
    "# KITTY_TELEGRAM_API_BASE_URL=https://api.telegram.org",
    "# KITTY_TELEGRAM_PROXY_URL=http://127.0.0.1:7897",
    "# KITTY_TELEGRAM_POLLING_TIMEOUT_SECONDS=50",
    "# KITTY_TELEGRAM_POLLING_LIMIT=100",
    "# KITTY_TELEGRAM_POLLING_RETRY_BACKOFF_MS=1000",
    "# KITTY_TELEGRAM_MESSAGE_CHUNK_CHARS=3500",
    "# KITTY_TELEGRAM_TYPING_INTERVAL_MS=4000",
    "# KITTY_TELEGRAM_DELIVERY_MAX_RETRIES=6",
    "# KITTY_TELEGRAM_DELIVERY_BASE_DELAY_MS=1000",
    "# KITTY_TELEGRAM_DELIVERY_MAX_DELAY_MS=30000",
    "",
    "# Runtime budget settings",
    "# Provider-facing budgets: tune these for the active model and relay.",
    "# Code still clamps invalid extremes so a broken .env cannot break the runtime.",
    "KITTY_CONTEXT_WINDOW_MESSAGES=160",
    "KITTY_MAX_CONTEXT_CHARS=900000",
    "KITTY_CONTEXT_SUMMARY_CHARS=120000",
    "KITTY_MAX_OUTPUT_TOKENS=384000",
    "",
    "# Tool IO budgets",
    "KITTY_MAX_READ_BYTES=120000",
    "KITTY_COMMAND_STALL_TIMEOUT_MS=30000",
    "KITTY_SHOW_REASONING=true",
    "",
    "# Agent profile settings",
    "# Built-in agent profile: intp",
    "KITTY_PROFILE=intp",
    "",
    "# Provider / model settings",
    "# Provider preset 1: YLS Codex + GPT-5.4",
    "# KITTY_PROVIDER=openai",
    `# ${kittyApiKeyLine}`,
    "# KITTY_BASE_URL=https://code.ylsagi.com/codex",
    "# KITTY_MODEL=gpt-5.4",
    "# KITTY_REASONING_EFFORT=xhigh",
    "# GPT reasoning effort: minimal | low | medium | high | xhigh",
    "",
    "# Provider preset 2: OpenAI relay + GPT-5.4",
    "# KITTY_PROVIDER=openai",
    `# ${kittyApiKeyLine}`,
    "# KITTY_BASE_URL=https://w.ciykj.cn",
    "# KITTY_MODEL=gpt-5.4",
    "# KITTY_REASONING_EFFORT=xhigh",
    "# GPT reasoning effort: minimal | low | medium | high | xhigh",
    "",
    "# Provider preset 3: DeepSeek official V4",
    "KITTY_PROVIDER=deepseek",
    kittyApiKeyLine,
    "KITTY_BASE_URL=https://api.deepseek.com",
    "KITTY_MODEL=deepseek-v4-flash",
    "KITTY_THINKING=enabled",
    "KITTY_REASONING_EFFORT=max",
    "# DeepSeek V4 model: deepseek-v4-flash | deepseek-v4-pro",
    "# DeepSeek V4 thinking: enabled | disabled",
    "# DeepSeek V4 reasoning effort: high | max",
    "",
    "# Provider preset 4: SiliconFlow + DeepSeek V3.2",
    "# KITTY_PROVIDER=openai-compatible",
    "# KITTY_API_KEY=replace-with-your-key",
    "# KITTY_BASE_URL=https://api.siliconflow.cn/v1",
    "# KITTY_MODEL=deepseek-ai/DeepSeek-V3.2",
    "",
  ].join("\n");
}
